### ISSUE TITLE
finish py quickstart docs and matching example py demos

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#119]
these are so close that they are the same issue.
Aim for examples 1d1 and 2d1 simple, and a guru, plus a single-prec demo.  Thanks!

**Comment by ahbarnett** [comment]
I'm having trouble even getting the basic higher-dim py wrappers to work on my ipython 3.7.7:

``
In [16]: f = finufftpy.nufft2d1(x, c, (1000,2000))                              
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-3b5ccd368522> in <module>
----> 1 f = finufftpy.nufft2d1(x, c, (1000,2000))

~/miniconda3/envs/idp/lib/python3.7/site-packages/finufftpy/_interfaces.py in nufft2d1(x, y, c, n_modes, out, eps, isign, **kwargs)
    642       see ``python/tests/accuracy_speed_tests.py``
    643     """
--> 644     return invoke_guru(2,1,x,y,None,c,None,None,None,out,isign,eps,n_modes,**kwargs)
    645 
    646 

~/miniconda3/envs/idp/lib/python3.7/site-packages/finufftpy/_interfaces.py in invoke_guru(dim, tp, x, y, z, c, s, t, u, f, isign, eps, n_modes, **kwargs)
    477     # infer n_modes/n_trans from input/output
    478     if tp==1:
--> 479         n_trans = valid_ntr(x,c)
    480         if n_modes is None and f is None:
    481             raise RuntimeError('FINUFFT type 1 input must supply n_modes or output vector, or both')

~/miniconda3/envs/idp/lib/python3.7/site-packages/finufftpy/_interfaces.py in valid_ntr(x, c)
    348 ### valid number of transforms
    349 def valid_ntr(x,c):
--> 350     n_trans = int(c.size/x.size)
    351     if n_trans*x.size != c.size:
    352         raise RuntimeError('FINUFFT c.size must be divisible by x.size')

AttributeError: 'tuple' object has no attribute 'size'
``

**Comment by ahbarnett** [comment]
I have basically done this. All 2D demos (and tutorial) are now rectangular so that they teach the right dim-ordering. The only thing I didn't do was a simple2d2.py to match that in the tutorial.
